#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        Richpolis\BackendBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ICC
        ROLE_ICC:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ICC, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: Richpolis\BackendBundle\Entity\Usuario, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/backend
            provider:    usuarios
            anonymous:      ~
            form_login:
                check_path: backend_check
                login_path: backend_login
                default_target_path: backend_homepage
                always_use_default_target_path: true
            logout:
                path:   backend_logout
                target: backend_login
        extranet:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: vip_login
                check_path: vip_login_check
                default_target_path: vip_login
                always_use_default_target_path: true
            logout:
                path:       vip_logout
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/*, roles: ROLE_ICC }
        - { path: ^/efconnect, role: ROLE_ICC }
        - { path: ^/elfinder, role: ROLE_ICC }
        - { path: ^/vip/pauta, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/vip/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/vip/*, role: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }


        